config/routes.rb
Rails.application.routes.draw do

  resources :tasks

  resources :bills, only: []
  authenticate :user do
    resources :invites
    resources :todos do
      member do
        put :complete, :incomplete
      end
    end
    resources :events
    resources :flats
    resources :bills, only: [:index, :create, :edit, :update, :destroy, :new, :show]
    get '/graphs', to: 'dashboard#graphs'
    get '/statistics', to: 'dashboard#statistics'
    get '/admin', to: 'dashboard#admin'
    get '/leave_flat', to: 'users#leave_flat'
  end
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users

  root 'dashboard#welcome'

end

app/models/flat.rb
class Flat < ActiveRecord::Base
  has_many :users
  has_many :invites
  has_many :tasks
  validates_presence_of :name, :on=>:create
  has_one :owner, class_name: "User"
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100#" }, :default_url => "/images/flat/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :set_flat, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def show
    @member = User.where(flat_id: @flat.id)
    respond_with(@flat)
  end

  def new
    @flat = Flat.new
    respond_with(@flat)
  end

  def create
    @flat = Flat.new(flat_params)
    @flat.save
    # If owner leaves, transfer ownership or delete flat?
    User.find(current_user).update(flat_id: @flat.id)
    @flat.update_attributes(owner: current_user)
    # @flat.owner = current_user ?
    respond_with(@flat)
  end

  def update
    @flat.update(flat_params)
    respond_with(@flat)
  end

  def destroy
    @flat.destroy
    respond_with(@flat)
    #prevent .. dump data to somewhere
  end

  private
    def set_flat
      @flat = Flat.find(params[:id])
    end

    def flat_params
      params.require(:flat).permit(:name, :owner, :avatar)
    end
end

app/helpers/flat_helper.rb
module FlatHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/_form.html.erb
<%= form_for(@flat) do |f| %>
    <% if @flat.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@flat.errors.count, "error") %> prohibited this flat from being saved:</h2>

          <ul>
            <% @flat.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </div>

    <div class="form">
      <%= f.label :avatar %>
      <%= f.file_field :avatar %>
    </div>

    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/flats/edit.html.erb
<h1>Editing flat</h1>

<%= render 'form' %>

<%= link_to 'Show', @flat %> |
<%= link_to 'Back', flats_path %>

app/views/flats/index.html.erb
<h1>Listing flats</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Owner</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @flats.each do |flat| %>
      <tr>
        <td><%= flat.name %></td>
        <td><%= flat.owner %></td>
        <td><%= link_to 'Show', flat %></td>
        <td><%= link_to 'Edit', edit_flat_path(flat) %></td>
        <td><%= link_to 'Destroy', flat, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Flat', new_flat_path %>

app/views/flats/new.html.erb
<h1>New flat</h1>

<%= render 'form' %>

<%= link_to 'Back', flats_path %>

app/views/flats/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <h1><%= @flat.name %></h1>
</p>

<%= link_to image_tag(Flat.find_by(id: current_user.flat_id).avatar.url(:medium), class: 'round-image-250'), flat_path(current_user.flat_id) if current_user.flat_id%>


<p>
  <strong>Members:</strong>
  <br>
  <% @member.each do |user| %>
    <td><%= user.name %></td>
    <td><%= user.balance %></td>
    <td><%= image_tag(user.avatar.url(:thumb), class: 'round-image-50')%></td>
    <br>
<%end %>
</p>
<br>
<%= bar_chart User.where(flat_id: current_user.flat_id).group(:name).sum(:balance) if current_user.flat_id%>
<p>
  <strong>Owner:</strong>
  <%= User.find_by(id: @flat.owner).name if  User.find_by(id: @flat.owner) %>
  <%= link_to image_tag(User.find_by(id: @flat.owner).avatar.url(:thumb), class: 'round-image-50'), User.find_by(id: @flat.owner) if  User.find_by(id: @flat.owner) %>
</p>


<%= link_to 'Edit', edit_flat_path(@flat), class: 'btn btn-default'  %>
<%= link_to 'Back', flats_path, class: 'btn btn-default'  %>
<%= link_to 'Leave Flat', leave_flat_path, class: 'btn btn-default'  %>