config/routes.rb
Rails.application.routes.draw do

  resources :tasks

  resources :bills, only: []
  authenticate :user do
    resources :invites
    resources :todos do
      member do
        put :complete, :incomplete
      end
    end
    resources :events
    resources :flats
    resources :bills, only: [:index, :create, :edit, :update, :destroy, :new, :show]
    get '/graphs', to: 'dashboard#graphs'
    get '/statistics', to: 'dashboard#statistics'
    get '/admin', to: 'dashboard#admin'
    get '/leave_flat', to: 'users#leave_flat'
  end
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users

  root 'dashboard#welcome'

end

app/models/bill.rb
class Bill < ActiveRecord::Base
  has_many :involved_in_bills
  has_many :users, :through => :involved_in_bills
  has_one :market
  validates :value, presence: true
  validates :market_id, presence: true
end

app/controllers/bills_controller.rb
class BillsController < ApplicationController

  respond_to :html

  def index
    flatmates = User.where(flat_id: current_user.flat_id)
    @bills = Bill.where(user_id: flatmates.map {|x|x.id}).paginate(page: params[:page], per_page: 5).order('id DESC')
    respond_with(@bills)
  end


  def show
    set_bill
    respond_with(@bill)
  end

  def new
    @bill = Bill.new
    respond_with(@bill)
  end

  def edit
    set_bill
  end

  def create
    @bill = Bill.new(bill_params)
    if @bill.save
      calculate_balance
      update_market_count
      flash[:success] = 'Succesfully created Bill'
    end
    respond_with(@bill)
  end

  def calculate_balance
    params[:bill][:payedby].reject!(&:empty?).each do |user_id|
      json = {'user_id' => "#{user_id}", 'bill_id' => "#{@bill.id}"}
      InvolvedInBill.new(json).save
    end
    InvolvedInBill.new({'user_id' => "#{@bill.user_id}", 'bill_id' => "#{@bill.id}"}).save
    @pos_user= User.find_by(id: params[:bill][:user_ids])
    frac_val = ((@bill.value)/((params[:bill][:payedby].size)))
    params[:bill][:payedby].each do |id|
      User.find_by(id: id).update_attributes(balance: "#{User.find_by(id: id).balance  - frac_val})")
    end
    @pos_user.update_attributes(balance: "#{User.find_by(id: params[:bill][:user_ids]).balance + @bill.value}")
  end

  def update_market_count
    Market.increment_counter(:count, params[:bill][:market_id])
  end

  def update
    set_bill
    @bill.update(bill_params)
    respond_with(@bill)
  end

  def destroy
    set_bill
    @bill.destroy
    respond_with(@bill)
  end

  private
  def set_bill
    @bill = Bill.find(params[:id])
  end

  def find_corresponding_user
    @user = User.where(id: @bill.user_id)
  end

  def bill_params
    params.require(:bill).permit(:value, :user_id, :market_id, :created_at, :note)
  end
end

app/helpers/bills_helper.rb
module BillsHelper
end

app/views/bills/_form.html.erb
<%= form_for(@bill) do |f| %>
    <% if @bill.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@bill.errors.count, "error") %> prohibited this bill from being saved:</h2>

          <ul>
            <% @bill.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">
      Create New Bill
    </button>

    <!-- Modal -->
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title" id="myModalLabel">New Bill</h4>
          </div>
          <div class="modal-body">
            <form class="form-horizontal">
              <div class="field form-group">
                <%= f.label :value %><br>
                <%= f.number_field :value, class: 'text_field', step: 'any' %>
              </div>

              <div class="field">
                <%= f.label :date %><br>
                <%= f.date_select :created_at %>
              </div>

              <div class="field">
                <%= f.hidden_field :user_id, :value => current_user.id %>
              </div>

              <div class="field">
                <%= f.label :pay_guy %><br>
                <%= f.select :user_ids, User.where(flat_id: current_user.flat_id).collect {|p| [ p.name, p.id ] } %>
              </div>


              <div class="field">
                <%= f.label :payedby %><br>
                <%= f.collection_check_boxes :payedby, User.where(flat_id: current_user.flat_id), :id, :name %>
              </div>

              <div class="field">
                <%= f.label :market_id %><br>
                <%= f.select :market_id, Market.all.collect {|p| [ p.name, p.id ] } %>
              </div>

              <div class="field">
                <%= f.label :note %><br>
                <%= f.text_field :note %>
              </div>

          </div>
          <div class="modal-footer">

            <div class="actions">
              <%= f.submit :class => 'btn btn-default'%>
            </div>
            </form>
<% end %>
<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
</div>
</div>
</div>
</div>

app/views/bills/edit.html.erb
<h1>Editing bill</h1>

<%= render 'form' %>

<%= link_to 'Show', @bill %> |
<%= link_to 'Back', bills_path %>

app/views/bills/index.html.erb
<h1>Listing bills</h1>

<table class="table table-hover table-bordered">
  <thead>
  <tr>
    <th>Value</th>
    <th>User</th>
    <th>Market</th>
    <th>Participants</th>
    <th>Note</th>
  </tr>
  </thead>

  <tbody>
  <% @bills.each do |bill| %>
      <tr>
        <td><%= bill.value %></td>
        <td><%= User.where(id: bill.user_id).first.name %></td>
        <td><%= Market.where(id: bill.market_id).first.name if bill.market_id && Market.where(id: bill.market_id).first %>
        <td>
          <% InvolvedInBill.usernames_by_bill_id(bill.id).each do |names| %>
              <%= names %>
          <%end%>
        </td>
        <td><%= bill.note %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<%= will_paginate @bills, renderer: BootstrapPagination::Rails %>
<br>

<%= link_to 'New Bill', new_bill_path , class: 'btn btn-default' %>

app/views/bills/new.html.erb
<!--<h1>New bill</h1>-->

<%= render 'form' %>

<!--<%= link_to 'Back', bills_path %>-->

app/views/bills/show.html.erb
<p id="notice"><%= notice %></p>

<p>

  <strong>Value:</strong>
  <%=number_with_precision(@bill.value, precision: 2) %>
</p>

<p>
  <strong>Payed by:</strong>
  <%= User.where(id: @bill.user_id).first.name %>
  Not correct if payer != current_user
</p>

<p>
  <strong>Market:</strong>
  <%= Market.where(id: @bill.market_id).first.name if Market.find_by(id: @bill.market_id)  %>
</p>
<%if @bill.note %>
    <p>
      <strong>Note:</strong>
      <%= @bill.note  %>
    </p>
<%end%>
<p>
  <strong>Participants:</strong>
  <% User.where(id: InvolvedInBill.where(bill_id: @bill.id).map {|user| user.user_id}).each do |user|  %>
      <%= user.name %>,
  <%end%>
</p>
<%= link_to 'Edit', edit_bill_path(@bill) %> |
<%= link_to 'Back', bills_path %>