config/routes.rb
Rails.application.routes.draw do

  resources :tasks

  resources :bills, only: []
  authenticate :user do
    resources :invites
    resources :todos do
      member do
        put :complete, :incomplete
      end
    end
    resources :events
    resources :flats
    resources :bills, only: [:index, :create, :edit, :update, :destroy, :new, :show]
    get '/graphs', to: 'dashboard#graphs'
    get '/statistics', to: 'dashboard#statistics'
    get '/admin', to: 'dashboard#admin'
    get '/leave_flat', to: 'users#leave_flat'
  end
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users

  root 'dashboard#welcome'

end

app/models/bill.rb
class Bill < ActiveRecord::Base
  has_many :involved_in_bills
  has_many :users, :through => :involved_in_bills
  has_one :market
  validates :value, presence: true
  validates :market_id, presence: true
end

app/models/event.rb
class Event < ActiveRecord::Base
  has_one :creator, class_name: User
  has_and_belongs_to_many :users
end

app/models/flat.rb
class Flat < ActiveRecord::Base
  has_many :users
  has_many :invites
  has_many :tasks
  validates_presence_of :name, :on=>:create
  has_one :owner, class_name: "User"
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100#" }, :default_url => "/images/flat/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/models/invite.rb
class Invite < ActiveRecord::Base
  belongs_to :flat
  belongs_to :sender, :class_name => 'User'
  belongs_to :recipient, :class_name => 'User'

  before_create :generate_token
  before_save :check_user_existence

  def generate_token
    self.token = Digest::SHA1.hexdigest([self.flat_id, Time.now, rand].join)
  end

  def check_user_existence
    recipient = User.find_by_email(email)
    if recipient
      self.recipient_id = recipient.id
    end
  end
end

app/models/involved_in_bill.rb
class InvolvedInBill < ActiveRecord::Base
  has_many :user
  has_many :bill

  def self.usernames_by_bill_id(bill_id)
    ids = InvolvedInBill.where(bill_id: bill_id).pluck(:user_id)
    User.where(id: ids).pluck(:name)
  end

end

app/models/market.rb
class Market < ActiveRecord::Base
  # belongs_to :bill ? why not ?
  validates :name, presence: true
end

app/models/task.rb
class Task < ActiveRecord::Base
  validates :name, presence: true
  validates :credit, presence: true
  validates :flat_id, presence: true
  belongs_to :flat
  has_many :working_on_tasks
  has_many :users, :through => :working_on_tasks
end

app/models/todo.rb
class Todo < ActiveRecord::Base
  validates :task, presence: true
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  require 'yaml'
  after_create :user_task_entry
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates_presence_of :name, :on=>:create
  has_and_belongs_to_many :events
  has_many :involved_in_bills
  has_many :bills, :through => :involved_in_bills
  belongs_to :flat
  has_many :todos
  has_many :invitations, :class_name => "Invite", :foreign_key => 'recipient_id'
  has_many :sent_invites, :class_name => "Invite", :foreign_key => 'sender_id'
  has_many :working_on_tasks
  has_many :tasks, :through => :working_on_tasks
  has_and_belongs_to_many :users, :join_table => "tasks_users"

  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100#" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  def user_task_entry
    file = 'config/user_tasks.yml'
    data = YAML::load_file(file)
    data.merge!(User.last.id => [])
    File.open(file, 'w') {|f| f.write data.to_yaml }
  end

end

app/models/working_on_task.rb
class WorkingOnTask < ActiveRecord::Base
  belongs_to :user
  belongs_to :task
end

app/controllers/bills_controller.rb
class BillsController < ApplicationController

  respond_to :html

  def index
    flatmates = User.where(flat_id: current_user.flat_id)
    @bills = Bill.where(user_id: flatmates.map {|x|x.id}).paginate(page: params[:page], per_page: 5).order('id DESC')
    respond_with(@bills)
  end


  def show
    set_bill
    respond_with(@bill)
  end

  def new
    @bill = Bill.new
    respond_with(@bill)
  end

  def edit
    set_bill
  end

  def create
    @bill = Bill.new(bill_params)
    if @bill.save
      calculate_balance
      update_market_count
      flash[:success] = 'Succesfully created Bill'
    end
    respond_with(@bill)
  end

  def calculate_balance
    params[:bill][:payedby].reject!(&:empty?).each do |user_id|
      json = {'user_id' => "#{user_id}", 'bill_id' => "#{@bill.id}"}
      InvolvedInBill.new(json).save
    end
    InvolvedInBill.new({'user_id' => "#{@bill.user_id}", 'bill_id' => "#{@bill.id}"}).save
    @pos_user= User.find_by(id: params[:bill][:user_ids])
    frac_val = ((@bill.value)/((params[:bill][:payedby].size)))
    params[:bill][:payedby].each do |id|
      User.find_by(id: id).update_attributes(balance: "#{User.find_by(id: id).balance  - frac_val})")
    end
    @pos_user.update_attributes(balance: "#{User.find_by(id: params[:bill][:user_ids]).balance + @bill.value}")
  end

  def update_market_count
    Market.increment_counter(:count, params[:bill][:market_id])
  end

  def update
    set_bill
    @bill.update(bill_params)
    respond_with(@bill)
  end

  def destroy
    set_bill
    @bill.destroy
    respond_with(@bill)
  end

  private
  def set_bill
    @bill = Bill.find(params[:id])
  end

  def find_corresponding_user
    @user = User.where(id: @bill.user_id)
  end

  def bill_params
    params.require(:bill).permit(:value, :user_id, :market_id, :created_at, :note)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/bills_helper.rb
module BillsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/flat_helper.rb
module FlatHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/helpers/invites_helper.rb
module InvitesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer navbar navbar-default navbar-fixed-bottom">
  <small>
    <a href="http://www.wgserv.eu/invoicer">Invoicer</a>
    by <a href="http://www.github.com/jschmid1">jaiks</a>
  </small>
  <nav>
    <ul>
      <li><a href="http://blog.wgserv.eu/">Blog</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "INVOICER", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav pull-right">
        <% if user_signed_in? %>
            <li><%= link_to('Admin', admin_path)if current_user.admin %></li>
            <%= link_to image_tag(current_user.avatar.url(:thumb), class: 'round-image-50'), current_user %>
            <% if current_user.flat_id  %>
                <i class="glyphicon glyphicon-plus text-success"></i>
            <%end%>
            <%= link_to image_tag(Flat.find_by(id: current_user.flat_id).avatar.url(:thumb), class: 'round-image-50'), flat_path(current_user.flat_id) if current_user.flat_id%>

            <li>
              <%= link_to('Dashboard', graphs_path)if current_user.flat_id %>
            </li>
            <li>
              <%= link_to('Statistics', statistics_path)if current_user.flat_id %>
            </li>
            <li>
              <%= link_to('Tasks', tasks_path)if current_user.flat_id %>
            </li>
            <li>
              <%= link_to('Create new bill', new_bill_path )if current_user.flat_id %>
            </li>
            <li>
              <%= link_to('List all bills', bills_path)if current_user.flat_id %>
            </li>
            <li>
              <%= link_to('Todos', todos_path) if current_user.flat_id %>
            </li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">

                <!--<li class="divider"></li>-->
                <li>
                  <%= link_to('Edit Profile', edit_user_registration_path) %>
                  <%= link_to('Invite to Flat', new_invite_path) if current_user.flat_id  %>
                  <%= link_to('Create new Flat', new_flat_path) unless current_user.flat_id %>
                  <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
                </li>
              </ul>
            </li>

        <% else %>
            <!--<%= link_to('Register', new_user_registration_path)  %>-->
            <!--<%= link_to('Login', new_user_session_path, class: 'btn btn-success')  %>-->

        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
</script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
<head>
  <title> Invoicer </title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <script src="//cdnjs.cloudflare.com/ajax/libs/moment.js/2.8.2/moment.min.js"></script>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
<%= render 'layouts/header' %>

<div class="container">
  <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "alert alert-#{key}") %>
  <% end %>
  <%= yield %>

</div>
<%= render 'layouts/footer' %>
</body>
</html>